{{-- GENERATED by `npm run tokens` from resources/js/theme. Do not edit by hand. --}}
{{-- Sets data-mode / data-role on <html> before first paint (no theme flash). --}}
<script>
(function () {
    var d = document.documentElement;
    var m = "light";
    try {
        var s = window.localStorage.getItem("duka.theme.mode");
        if (s === 'light' || s === 'dark' || s === 'system') m = s;
    } catch (e) {}
    if (m === 'system') {
        m = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }
    var roles = {"admin":"admin","seller":"seller","stockkeeper":"stock_keeper","stock":"stock_keeper","delivery":"delivery","vendor":"vendor","finance":"finance","procurement":"procurement","marketing":"marketing","dev":"dev","shared":"shared"};
    var p = window.location.hostname.toLowerCase().split('.');
    var r = (p.length > 2 && roles[p[0]]) || "admin";
    d.setAttribute('data-mode', m);
    d.setAttribute('data-role', r);
})();
</script>
