services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Duka_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - storage_data:/var/www/html/storage
      - vendor_data:/var/www/html/vendor
    depends_on:
      - db
    networks:
      - duka-network

  db:
    image: mysql:8.0
    container_name: Duka_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dukapass
      MYSQL_DATABASE: duka
      MYSQL_USER: dukauser
      MYSQL_PASSWORD: dukapass
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - duka-network

networks:
  duka-network:

volumes:
  database_data:
  vendor_data:
  storage_data:
