services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Duka_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - duka-network

  db:
    image: mysql:8.0
    container_name: Duka_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dukapass
      MYSQL_DATABASE: duka
      MYSQL_USER: dukauser
      MYSQL_PASSWORD: dukapass
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - duka-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10

  tunnel:
      image: cloudflare/cloudflared:latest
      container_name: Duka_tunnel
      restart: always
      # Force IPv4 inside the container to avoid the network unreachable error
      command: tunnel --config /home/nonroot/.cloudflared/config.yml --no-autoupdate --edge-ip-version 4 run
      volumes:
        - ./config/cloudflared:/home/nonroot/.cloudflared
      networks:
        - duka-network
      depends_on:
        - app

networks:
  duka-network:

volumes:
  database_data:
  vendor_data:
  storage_data:
  node_modules_data:
