FROM php:8.4-apache

WORKDIR /var/www/html

# System deps
RUN apt-get update && apt-get install -y \
    git unzip zip curl \
    nodejs npm \
    default-mysql-client \
    libpng-dev libonig-dev libxml2-dev libzip-dev \
    libicu-dev libbz2-dev libgmp-dev libldap2-dev \
    libpq-dev libxslt1-dev libtidy-dev \
    libsodium-dev libsnmp-dev snmp \
    libfreetype6-dev libjpeg62-turbo-dev \
    pkg-config \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
    pdo pdo_mysql

# Apache config (same as prod)
RUN a2enmod rewrite headers ssl \
    && sed -i 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/000-default.conf

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

CMD ["apache2-foreground"]
