<?php

namespace Database\Seeders\Admin;

use App\Models\Item\Item;
use App\Models\Item\ItemColor;
use App\Models\Item\ItemPackagingType;
use App\Models\Item\ItemSize;
use App\Models\Item\ItemVariant;
use Exception;
use Illuminate\Database\Seeder;

class ItemSeeder2 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Example product names
        $productNames = [
            // //////////////////////////
            // # '2 side color',
            // //////////////////////////P
            // '2025 -1',
            // '2025 ብልጭልጭ',
            // '25k - 1 ፓሪስ',
            // '25k- 5 ጨርቅ ማስታወሻ',
            // //////////////////////////
            'Noteit',
            'Ring',
            // //////////////////////////
            // '3 subject',
            // '4 subject',
            // '5 subject',
            // //////////////////////////
            // '3*3 noteit',
            // '3*4 noteit',
            // '3*5 noteit',
            // '3*4',
            // //////////////////////////
            // '335 Kangaroo Stapler',
            // '435 Kangaroo Stapler',
            // '9*7',
            // //////////////////////////
            // '6 columns',
            // 'A3 laola',
            // 'A3 road map',
            // 'A4 binding file ዉዱ',
            // 'A4 gold on',
            // 'A4 laola',
            // 'A4 post',
            // 'A4 posta',
            // 'A5 - 10 ባለቀለበት',
            // 'A5 - 12 ባለ ፓኬት',
            // 'A5 - 9 ባለ ማግኔት ጌጥ',
            // 'A5 - ሳንቲም',
            // 'A5 -2 ባለ እስክርቢቶ',
            // 'A5 post',
            // 'A5 subject new',
            // 'A5 ብልጭልጭ 25k - 9',
            // 'A5 ገመድ new',
            // 'A5- 8 ባለሳንቲም ባለእስክርቢቶ',
            // 'A5-11-1 ጠንካራ ከቨር ያለዉ',
            // 'A5-5 ባለ ማብኔት ነጭ',
            // 'A6 ባለ ገመድ',
            // 'A6 ብልጭልጭ',
            // 'A6- 1 ባለ ገመድ',
            // 'A6- 1 ባለቁልፍ',
            // 'A6- 2 ባለ ገመድ ብልጭልጭ ያለዉ',
            // 'A6- 2 ባለ ገመድ',
            // 'A6- 3 ባለገመድ',
            // 'A6- ቁልፍ የድሮ',
            // 'Acleric',
            // 'Agenda አጀንዳ',
            // 'Atlas Film አትላስ ፌልም',
            // 'B5 - 1 ሳንቲም',
            // 'B5 - ሳንቲም',
            // 'B5 ባለ ሳንቲም ኖርማል',
            // 'B5- ባለ ሳንቲም እስክርቢቶ ማስገቢያ ያለዉ',
            // 'B5-1 ባለማግኔት ጫፉ ነጭ',
            // 'B5-2 ባለማግኔት ጌጥ',
            // 'B5-3 ባለማግኔት ብረት',
            // 'B5-5 ቀጭን ሳንቲም',
            // 'Bic Pen Black ቢክ እስኪብርቶ ጥቁር',
            // 'Bic Pen Blue ቢክ እስኪብርቶ ሰማያዊ',
            // 'Bj ባለ 300 ብር',
            // //////////////////////////
            // 'Box File',
            // //////////////////////////
            // 'Box file Black',
            // 'Box file Color',
            // 'Business Card ቢዝነስ ካርድ',
            // 'Cilp file',
            // 'Clipboard Cheap ርካሹ ክሊፕ ቦርድ',
            // 'Color Bad 2 pockets ክሊር ባግ ባለ 2 ኪስ',
            // 'Color Bag ክሊር ባግ ርካሹ',
            // 'Coloring book ባለ-ብሪሽ',
            // 'Coloring Book',
            // 'Compass 3009 ማይካ',
            // 'Compass 8005 ማይካ',
            // 'Compass 8010',
            // 'Compass color b',
            // 'Compass ፕላስቲክ 5007',
            // 'Crayon normal',
            // 'Crayon ምሳቃ ከለር በእቃ',
            // 'Cutter Small ከተር ትልቁ',
            // 'Diamond pen ዳይመንድ እስኪብርቶ',
            // 'Diary Code ዲያሪ ኮድ',
            // 'Diary Small ዲያሪ ትንሹ',
            // 'Diary ዲያሪ የተለያየ',
            // 'Diary ዲያሪ ፍሩት',
            // //////////////////////////
            // 'Dispencer big',
            // 'Dispencer Medium ዲስፔስር መካከለኛ',
            // 'Dispencer small',
            // //////////////////////////
            // 'Display book 100',
            // 'Display book 40',
            // 'Display book 60',
            // 'Display book 80',
            // 'Diary small',
            // 'Document Case',
            // 'Drawing Book Long የስዕል ደብተር ረጅሙ',
            // 'Drawing Book Short የስዕል ደብተር አጭሩ',
            // 'Elastic band',
            // 'Erasor Shaped ላጲስ ባለቅርፅ',
            // 'Eyeye pan',
            // 'Fastener',
            // 'Fixer 0.5 ፊክሰር 5 ቁጥር',
            // 'Fixer 0.7 ፊክሰር 7 ቁጥር',
            // 'Flexible 20cm',
            // 'Fluid normal',
            // 'Folder 12 pockets ፎልበር 12 ኪስ',
            // 'Folder 7 Pockets ባለ 7 ኪስ ፎልደር',
            // 'Folder with rough texture ሸካራ ፎልደር',
            // 'Globe ግሎብ',
            // 'Hand Writing',
            // 'Hard cover',
            // 'Laminating 65*95',
            // 'Laminating 76*106',
            // 'Laminating a3',
            // 'Lead 0.5 ሊድ 0.5 ቁጥር',
            // 'Lead 0.7 ሊድ 0.7 ቁጥር',
            // 'Magazin Rack ማጋዚን ራክ የሚገጠም',
            // 'Magazine Rack መጋዘን ራክ የተበተነ',
            // 'Marker 1 side',
            // 'Marker 2 side',
            // 'Marker 2 side',
            // 'Marshale compass',
            // 'NoteBook 18k Black ማስታወሻ 18k ጥቁር',
            // 'NoteBook 25k Leather Expensive ማስታወሻ 25k ሌዘር ዉዱ',
            // 'NoteBook 32k color',
            // 'NoteBook 32k normal ማስታወሻ 32k normal',
            // 'NoteBook 32k ጥቁር',
            // 'NoteBook 60k ማስታወሻ 60k',
            // 'NoteBook A4 ማስታወሻ A4 መዝገብ 200',
            // 'NoteBook A5 Magnet New ማስታወሻ A5 ማግኔት new',
            // 'NoteBook A5 Metal Magnet ማስታወሻ A5 ብረት ማግኔት',
            // 'NoteBook A5 Paris ማስታወሻ A5 ፓሪስ',
            // 'NoteBook A5 ማስታወሻ A5 ባለ new ማግኔት',
            // 'NoteBook A5 ማስታወሻ A5 ባለ new ገመድ',
            // 'Notebook A5 ማስታወሻ ባለ ዉሃ',
            // 'NoteBook A5-1 ማስታወሻ A5-1 ባለ ማግኔት',
            // 'NoteBook A5-11 ማስታወሻ A5- 11 ሄሎ subject',
            // 'NoteBook A5-6 Magnet Metal ማስታወሻ A5- 6 ጫፉ ነጭ ብረት ማግኔት',
            // 'NoteBook A5-7 Magnet Metal ማስታወሻ A5-7 ብረት ማግኔት',
            // 'NoteBook A6 100 ማስታወሻ A6 100',
            // 'NoteBook A6 Magnet New ማስታወሻ A6 ማግኔት new',
            // 'NoteBook A6 Ribbon ማስታወሻ A6 ገመድ የድሮ',
            // 'NoteBook A6 ማስታወሻ A6 ባለ 1 ለእስክርቢቶ',
            // 'NoteBook B5 Old ማስታወሻ የድሮ',
            // 'NoteBook B5-2 with pen ማስታወሻ B5-2 ባለ እስክርቢቶ',
            // 'NoteBook B5-4 Magnet Metal ማስታወሻ B5-4 ማግኔት ብረት',
            // 'NoteBook ማስታወሻ እንጨት',
            // 'Office pin',
            // 'Oil color',
            // 'Paint Brush የስዕል ብሩሽ',
            // 'Pan box hello',
            // 'Paper tray 2 ማይካ',
            // 'Paper tray 3 ማይካ',
            // 'Paper tray 3 ብረት 2001',
            // 'Pencil Bag ሸራ ፔንስል ባግ',
            // 'Pencil Bag ፔንስል ባግ ማይካ ባለ መቅተጫ',
            // 'Pencil Bag ፔንስል ባግ ሻራ ጠንካራዉ',
            // 'Pencil Color 2 sided',
            // 'Pencil Color እርሳስ ከለር አጭሩ',
            // 'Pencil Nann እርሳስ',
            // 'Pencil Vneeds እርሳስ',
            // 'Pencil እርሳስ ባለ እቃ',
            // 'Pencil እርሳስ የስዕል ቁጥሩ የተለያየ',
            // 'Piko ምሳቃ color',
            // 'Plaster Cutter የእጅ ፕላስተር መቁረጫ ውዱ',
            // 'Popit',
            // 'Popit',
            // 'Price Tag ዋጋ መለጠፊያ',
            // 'Puncher Small ፓንቸር ትንሹ',
            // 'Remover',
            // 'Ring 10 ረንግ 10',
            // 'Ring 12 ሪንግ 12',
            // 'Ring 14 ሪንግ 14',
            // 'Ring 16 ሪንግ 16',
            // 'Ring 18 ሪንግ 18',
            // 'Ring 20 ሪንግ 20',
            // 'Ring 6 ሪንግ 6',
            // 'Ring 8 ሪንግ 8',
            // 'Rotring Eraser ሮተሪንግ ላጲስ',
            // 'Ruler 30 cm normal',
            // 'Ruler 30 cm ማስመሪያ 30 cm ጠንካራዉ',
            // 'Ruler 50 cm ማስመሪያ 50 cm',
            // 'Scissor Big መቀስ ትልቁ ባለክዳን',
            // 'Scissor Kids የህፃናት መቀስ',
            // 'Scissor Small ትንሹ መቀስ',
            // 'Scissors መካከለኝ መቀስ',
            // 'Set Square 35 cm ሴትእስኩዊር 35 cm',
            // 'Set Square Yellow ሲትስኬር ቢጫ',
            // 'Set Square ቢጫ ሴትስኬር ማርከር ያለዉ እና የሌለዉ',
            // 'Sharpner with a Brush ባለ ቡሩሽ መቅረጫ',
            // 'Sharpner መቅረጫ',
            // 'Stapler gold',
            // 'Stapler ርካሹ',
            // 'T square 60cm',
            // 'Ticket ትኬት',
            // 'Ticket ትኬት',
            // 'Transparency Color ትራንስፓረንሲ ከለር',
            // 'Transparency White ትራንስፓረንሲ ነጭ',
            // 'Triangular ruler 30 cm 144',
            // 'Triangular ruler 30 cm 288',
            // 'Water Color ዉሃ ከለር ዉዱ ፍጭጭ የሚለዉ',
            // 'Water color',
            // 'White Board Marker',
            // 'Yuanyuan Marker',
            // 'ምሳቃ color ተንጠልጣይ',
            // 'ምሳቃ ከለር piko',
            // 'ሰፈነግ ( የብር መቁጠሪያ)',
            // 'ሽት ትፖቴክተር',
            // 'ቆርቆሮ ኮምፓስ',
            // 'እርኬል ማስመሪያ',
            // 'ከተር ትንሹ',
            // 'ክሊፕቦርድ ርካሹ',
            // 'ዉሃ ከለር ውዱትልቁ ፕንስል ባግ ሸራ',
            // 'የስጦታ ማስታወሻ የተሰራ',
            // 'የውብዳር ከለር',
            // 'ጥቁር ኮምፓስ',
            // 'ጥቁር የስዕል እርሳስ',
            // 'ጥጥ ማስታወሻ',
            // 'ፓንቸር ትንሹ 520',
            // 'ፓንቸር ትንቁ 520',

            // -----------------------------------------------------------------------------------------------------------------

            // 'Dispencer big',
            // 'Dispencer small',
            // 'Water color',
            // 'Oil color',
            // '9*7',
            // 'Hard cover',
            // 'Office pin',
            // 'Stapler gold',
            // 'Elastic band',
            // 'Triangular ruler 30 cm 288',
            // 'Triangular ruler 30 cm 144',
            // 'T square 60cm',
            // 'Ruler 30 cm normal',
            // 'Crayon normal',
            // 'Bic Pen Blue ቢክ እስኪብርቶ ሰማያዊ',
            // 'Bic Pen Black ቢክ እስኪብርቶ ጥቁር',
            // '3 subject',
            // '4 subject',
            // '5 subject',
            // '3*3 noteit',
            // '3*4 noteit',
            // '3*5 noteit',

            // 'Set Square ቢጫ ሴትስኬር ማርከር ያለዉ እና የሌለዉ',
            // 'Flexible 20cm',
            // 'Crayon ምሳቃ ከለር በእቃ',
            // 'A4 laola',
            // 'A3 road map',
            // 'A3 laola',
            // 'A5 subject new',

            // 'A4 gold on',
            // 'A5 post',
            // 'B5-2 ባለማግኔት ጌጥ',
            // 'A6 ብልጭልጭ',
            // 'Acleric',

            // 'Magazin Rack ማጋዚን ራክ የሚገጠም',

            // 'Price Tag ዋጋ መለጠፊያ',
            // 'Laminating 76* 106',
            // 'Cilp file',
            // 'Diyer small',
            // 'Fluid normal',
            // 'Laminating 65*95',

            // 'Stapler ርካሹ',

            // 'Fastener',
            // 'White Board Marker',
            // 'ክሊፕቦርድ ርካሹ',
            // 'የውብዳር ከለር',
            // 'ምሳቃ ከለር piko',
            // 'Remover',
            // 'Marker 2 side',
            // 'ከተር ትንሹ',
            // 'ቆርቆሮ ኮምፓስ',
            // 'Agenda አጀንዳ',
            // 'A4 post',

            // 'Ruler 50 cm ማስመሪያ 50 cm',
            // 'ፓንቸር ትንሹ 520',
            // 'ፓንቸር ትንቁ 520',
            // 'Transparency Color ትራንስፓረንሲ ከለር',
            // 'Transparency White ትራንስፓረንሲ ነጭ',
            // 'Atlas Film አትላስ ፌልም',

            // 'B5-5 ቀጭን ሳንቲም',
            // '2025 -1',
            // '2025 ብልጭልጭ',
            // 'Diamond pen ዳይመንድ እስኪብርቶ',
            // 'B5 ባለ ሳንቲም ኖርማል',
            // 'B5-3 ባለማግኔት ብረት',
            // 'B5-1 ባለማግኔት ጫፉ ነጭ',
            // 'A5-5 ባለ ማብኔት ነጭ',
            // 'A6 ባለ ገመድ',

            // 'ጥቁር ኮምፓስ',

            // 'Set Square Yellow ሲትስኬር ቢጫ',
            // 'Set Square 35 cm ሴትእስኩዊር 35 cm',
            // 'NoteBook 32k color',
            // 'A5 - 10 ባለቀለበት',
            // 'A5 - 12 ባለ ፓኬት',
            // '25k- 5 ጨርቅ ማስታወሻ',
            // 'A5 - 9 ባለ ማግኔት ጌጥ',
            // '25k - 1 ፓሪስ',
            // 'A6- 2 ባለ ገመድ',
            // 'A6- 1 ባለቁልፍ',
            // 'A5- 8 ባለሳንቲም ባለእስክርቢቶ',
            // 'A6- 1 ባለ ገመድ',
            // 'A5 - ሳንቲም',
            // 'B5 - ሳንቲም',
            // 'A6- ቁልፍ የድሮ',
            // 'Box file Color',
            // 'Box file Black',
            // 'Ticket ትኬት',
            // 'A6- 2 ባለ ገመድ ብልጭልጭ ያለዉ',
            // 'A6- 3 ባለገመድ',
            // 'Ruler 30 cm ማስመሪያ 30 cm ጠንካራዉ',
            // 'A5 ብልጭልጭ 25k - 9',

            // 'Marshale compass',

            // 'Fixer 0.7 ፊክሰር 7 ቁጥር',
            // 'Fixer 0.5 ፊክሰር 5 ቁጥር',
            // 'እርኬል ማስመሪያ',
            // 'ጥቁር የስዕል እርሳስ',
            // 'Lead 0.7 ሊድ 0.7 ቁጥር',
            // 'Lead 0.5 ሊድ 0.5 ቁጥር',
            // 'Paint Brush የስዕል ብሩሽ',
            // 'Pencil Color 2 sided',
            // 'Yuanyuan Marker',
            // 'Laminating a3',
            // 'Rotring Eraser ሮተሪንግ ላጲስ',
            // 'Coloring Book',
            // 'Document Case',
            // 'Erasor Shaped ላጲስ ባለቅርፅ',
            // 'Coloring book ባለ-ብሪሽ',
            // 'B5 - 1 ሳንቲም',
            // 'B5- ባለ ሳንቲም እስክርቢቶ ማስገቢያ ያለዉ',

            // 'Sharpner መቅረጫ',
            // 'Popit',
            // 'ጥጥ ማስታወሻ',
            // 'Bj ባለ 300 ብር',
            // '6 columns',

            // 'የስጦታ ማስታወሻ የተሰራ',

            // 'Ring 6 ሪንግ 6',
            // 'Ring 8 ሪንግ 8',
            // 'Ring 10 ረንግ 10',
            // 'Ring 12 ሪንግ 12',
            // 'Ring 14 ሪንግ 14',
            // 'Ring 16 ሪንግ 16',
            // 'Ring 18 ሪንግ 18',
            // 'Ring 20 ሪንግ 20',

            // 'Diary Small ዲያሪ ትንሹ',
            // 'Diary Code ዲያሪ ኮድ',
            // 'Diary ዲያሪ ፍሩት',
            // 'Diary ዲያሪ የተለያየ',

            // 'Display book 40',
            // 'Display book 60',
            // 'Display book 80',
            // 'Display book 100',

            // 'Color Bag ክሊር ባግ ርካሹ',
            // 'NoteBook 32k ጥቁር',
            // 'Folder with rough texture ሸካራ ፎልደር',
            // 'A5 -2 ባለ እስክርቢቶ',

            // 'Pencil Bag ፔንስል ባግ ማይካ ባለ መቅተጫ',
            // 'Pencil Bag ሸራ ፔንስል ባግ',
            // 'Pencil Bag ፔንስል ባግ ሻራ ጠንካራዉ',

            // 'Pencil እርሳስ የስዕል ቁጥሩ የተለያየ',
            // 'Pencil Vneeds እርሳስ',
            // 'Pencil Nann እርሳስ',
            // 'Pencil እርሳስ ባለ እቃ',
            // 'Pencil Color እርሳስ ከለር አጭሩ',

            // 'ሽት ትፖቴክተር',
            // 'Business Card ቢዝነስ ካርድ',
            // '335-',
            // 'A5-11-1 ጠንካራ ከቨር ያለዉ',
            // 'Puncher Small ፓንቸር ትንሹ',

            // '435-',
            // 'Water Color ዉሃ ከለር ዉዱ ፍጭጭ የሚለዉ',

            // 'Scissors መካከለኝ መቀስ',
            // 'Scissor Small ትንሹ መቀስ',
            // 'Scissor Kids የህፃናት መቀስ',
            // 'Scissor Big መቀስ ትልቁ ባለክዳን',

            // 'Folder 7 Pockets ባለ 7 ኪስ ፎልደር',

            // 'NoteBook B5-2 with pen ማስታወሻ B5-2 ባለ እስክርቢቶ',
            // 'NoteBook A6 Ribbon ማስታወሻ A6 ገመድ የድሮ',
            // 'NoteBook A5-11 ማስታወሻ A5- 11 ሄሎ subject',
            // 'NoteBook A5-7 Magnet Metal ማስታወሻ A5-7 ብረት ማግኔት',
            // 'NoteBook A5-6 Magnet Metal ማስታወሻ A5- 6 ጫፉ ነጭ ብረት ማግኔት',
            // 'NoteBook B5-4 Magnet Metal ማስታወሻ B5-4 ማግኔት ብረት',
            // 'NoteBook A6 ማስታወሻ A6 ባለ 1 ለእስክርቢቶ',
            // 'NoteBook A5 ማስታወሻ A5 ባለ new ማግኔት',
            // 'NoteBook A5 ማስታወሻ A5 ባለ new ገመድ',
            // 'NoteBook B5 Old ማስታወሻ የድሮ',
            // 'Notebook A5 ማስታወሻ ባለ ዉሃ',
            // 'NoteBook A5 Magnet New ማስታወሻ A5 ማግኔት new',
            // 'NoteBook A5 Paris ማስታወሻ A5 ፓሪስ',
            // 'NoteBook 25k Leather Expensive ማስታወሻ 25k ሌዘር ዉዱ',
            // 'NoteBook A5 Metal Magnet ማስታወሻ A5 ብረት ማግኔት',
            // 'NoteBook A6 Magnet New ማስታወሻ A6 ማግኔት new',
            // 'NoteBook 60k ማስታወሻ 60k',
            // 'NoteBook 32k normal ማስታወሻ 32k normal',
            // 'NoteBook 18k Black ማስታወሻ 18k ጥቁር',
            // 'NoteBook A6 100 ማስታወሻ A6 100',
            // 'NoteBook A5-1 ማስታወሻ A5-1 ባለ ማግኔት',
            // 'NoteBook A4 ማስታወሻ A4 መዝገብ 200',
            // 'NoteBook ማስታወሻ እንጨት',

            // 'Sharpner with a Brush ባለ ቡሩሽ መቅረጫ',
            // 'ሰፈነግ ( የብር መቁጠሪያ)',
            // 'Magazine Rack መጋዘን ራክ የተበተነ',

            // 'Paper tray 2 ማይካ',
            // 'Paper tray 3 ማይካ',
            // 'Paper tray 3 ብረት 2001',

            // 'Globe ግሎብ',
            // 'Marker 1 side',
            // 'Marker 2 side',
            // 'Compass 3009 ማይካ',

            // 'Color Bad 2 pockets ክሊር ባግ ባለ 2 ኪስ',

            // 'Folder 12 pockets ፎልበር 12 ኪስ',

            // 'Cutter Small ከተር ትልቁ',
            // 'Compass ፕላስቲክ 5007',
            // 'Compass 8010',
            // 'Compass color b',
            // 'Compass 8005 ማይካ',
            // 'Plaster Cutter የእጅ ፕላስተር መቁረጫ ውዱ',
            // 'A4 posta',

            // 'ዉሃ ከለር ውዱትልቁ ፕንስል ባግ ሸራ',

            // 'Eyeye pan',
            // 'A5 ገመድ new',
            // 'Dispencer Medium ዲስፔስር መካከለኛ',
            // '2 side colore ዉዱ',
            // '3*4',

            // 'Popit',
            // 'ምሳቃ color ተንጠልጣይ',
            // 'Clipboard Cheap ርካሹ ክሊፕ ቦርድ',

            // 'Pan box hello',
            // 'A4 binding file ዉዱ',
            // 'Piko ምሳቃ color',

            // 'Ticket ትኬት',
            // 'Drawing Book Short የስዕል ደብተር አጭሩ',
            // 'Drawing Book Long የስዕል ደብተር ረጅሙ',
            // 'Hand Writing'

        ];

        $productNames = [
            // 1, '2025 - 1',
            // 2, '2025 - ብልጭልጭ',
            // 3, '25k - 1 ፓሪስ',
            // 4, '25k - 5 ጨርቅ ማስታወሻ',
            // 5, 'A3 - Laola',
            // 6, 'A3 - Road map',
            // 7, 'A4 - Binding file ዉዱ',
            // 8, 'A4 - Gold on',
            // 9, 'A4 - Laola',
            // 10, 'A4 - Post',
            // 11, 'A5 - 10 ባለቀለበት',
            // 12, 'A5 - 11 - 1 ጠንካራ ከቨር ያለዉ',
            // 13, 'A5 - 12 ባለ ፓኬት',
            // 14, 'A5 - 2 ባለ እስክርቢቶ',
            // 15, 'A5 - 5 ባለ ማብኔት ነጭ',
            // 16, 'A5 - 8 ባለሳንቲም ባለእስክርቢቶ',
            // 17, 'A5 - 9 ባለ ማግኔት ጌጥ',
            // 18, 'A5 - ብልጭልጭ 25k - 9',
            // 19, 'A5 - ገመድ new',
            // 20, 'A5 - ሳንቲም',
            // 21, 'A6 - 1 ባለ ገመድ',
            // 22, 'A6 - 1 ባለቁልፍ',
            // 23, 'A6 - 2 ባለ ገመድ',
            // 24, 'A6 - 2 ባለ ገመድ ብልጭልጭ ያለዉ',
            // 25, 'A6 - 3 ባለገመድ',
            // 26, 'A6 - ብልጭልጭ',
            // 27, 'A6 - ባለ ገመድ',
            // 28, 'A6 - ቁልፍ የድሮ',
            // 29, 'Acleric',
            // 30, 'Agenda አጀንዳ',
            // 31, 'Atlas Film አትላስ ፌልም',
            // 32, 'B5 - 1 ባለማግኔት ጫፉ ነጭ',
            // 33, 'B5 - 1 ሳንቲም',
            // 34, 'B5 - 2 ባለማግኔት ጌጥ',
            // 35, 'B5 - 3 ባለማግኔት ብረት',
            // 36, 'B5 - 5 ቀጭን ሳንቲም',
            // 37, 'B5 - ባለ ሳንቲም ኖርማል',
            // 38, 'B5 - ባለ ሳንቲም እስክርቢቶ ማስገቢያ ያለዉ',
            // 39, 'B5 - ሳንቲም',
            // 40, 'Bj ባለ 300 ብር',
            // 41, 'Box file - Black/Color',
            // 42, 'Business Card ቢዝነስ ካርድ',
            // 43, 'Cilp file',
            // 44, 'ClipBoard',
            // 45, 'ClipBoard - ክሊፕቦርድ ርካሹ',
            // 46, 'Color - 2 side Color',
            // 47, 'Color - Oil',
            // 48, 'Color - Piko ምሳቃ',
            // 49, 'Color - ምሳቃ ከለር ተንጠልጣይ',
            // 50, 'Color - ዉሃ ከለር ውዱ ትልቁ',
            // 51, 'Color Bad - 2 pockets ክሊር ባግ ባለ 2 ኪስ',
            // 52, 'Color Bag - ክሊር ባግ ርካሹ',
            // 53, 'Coloring Book',
            // 54, 'Coloring Book - ባለ ብሩሽ',
            // 55, 'Compass - 3009 ማይካ',
            // 56, 'Compass - 8005 ማይካ',
            // 57, 'Compass - 8010',
            // 58, 'Compass - Color b',
            // 59, 'Compass - Marshale',
            // 60, 'Compass - ቆርቆሮ ኮምፓስ',
            // 61, 'Compass - ጥቁር ኮምፓስ',
            // 62, 'Compass - ፕላስቲክ 5007',
            // 63, 'Crayon - Normal',
            // 64, 'Crayon - ምሳቃ ከለር በእቃ',
            // 65, 'Cutter - Small ከተር ትልቁ',
            // 66, 'Cutter - Small ከተር ትንሹ',
            // 67, 'Diary - Code ዲያሪ ኮድ',
            // 68, 'Diary - Small ዲያሪ ትንሹ',
            // 69, 'Diary - ዲያሪ ፍሩት',
            // 70, 'Diary - ዲያሪ የተለያየ',
            // 71, 'Dispencer big/Medium/small ዲስፔስር',
            // 72, 'Display book - 100',
            // 73, 'Display book - 40',
            // 74, 'Display book - 60',
            // 75, 'Display book - 80',
            // 76, 'Document Case',
            // 77, 'Drawing Book - Long የስዕል ደብተር ረጅሙ',
            // 78, 'Drawing Book - Short የስዕል ደብተር አጭሩ',
            // 79, 'Elastic Band - የብር ላስቲክ',
            // 80, 'Erasor Shaped ላጲስ ባለቅርፅ',
            // 81, 'Eyeye Pan',
            // 82, 'Fastener',
            // 83, 'Fixer (0.5/0.7) ፊክሰር (5/7) ቁጥር',
            // 84, 'Flexible 20cm',
            // 85, 'Fluid Normal',
            // 86, 'Folder - 12 pockets ፎልበር 12 ኪስ',
            // 87, 'Folder - 7 Pockets ባለ 7 ኪስ ፎልደር',
            // 88, 'Folder with rough texture ሸካራ ፎልደር',
            // 89, 'Globe ግሎብ',
            // 90, 'Hand Writing',
            // 91, 'Hard Cover',
            // 92, 'Laminating 65*95',
            // 93, 'Laminating 76*106',
            // 94, 'Laminating A3',
            // 95, 'Lead (0.5/0.7) ሊድ (0.5/0.7) ቁጥር',
            // 96, 'Magazine Rack - ማጋዚን ራክ የሚገጠም',
            // 97, 'Magazine Rack - መጋዘን ራክ የተበተነ',
            // 98, 'Marker - (1/2) Side',
            // 99, 'Marker - White Board',
            // 100, 'Marker - Yuanyuan',
            // 101, 'NoteBook - ማስታወሻ እንጨት',
            // 102, 'NoteBook - ጥጥ ማስታወሻ',
            // 103, 'NoteBook 18k - Black ማስታወሻ 18k ጥቁር',
            // 104, 'NoteBook 25k - Leather Expensive ማስታወሻ 25k ሌዘር ዉዱ',
            // 105, 'NoteBook 32k - Color',
            // 106, 'NoteBook 32k - Normal ማስታወሻ 32k normal',
            // 107, 'NoteBook 32k - ጥቁር',
            // 108, 'NoteBook 60k - ማስታወሻ 60k',
            // 109, 'NoteBook A4 - ማስታወሻ A4 መዝገብ 200',
            // 110, 'NoteBook A5 - 1 ማስታወሻ A5-1 ባለ ማግኔት',
            // 111, 'NoteBook A5 - 6 Magnet Metal ማስታወሻ A5- 6 ጫፉ ነጭ ብረት ማግኔት',
            // 112, 'NoteBook A5 - 7 Magnet Metal ማስታወሻ A5-7 ብረት ማግኔት',
            // 113, 'NoteBook A5 - Magnet New ማስታወሻ A5 ማግኔት new',
            // 114, 'NoteBook A5 - Metal Magnet ማስታወሻ A5 ብረት ማግኔት',
            // 115, 'NoteBook A5 - Paris ማስታወሻ A5 ፓሪስ',
            // 116, 'NoteBook A5 - ማስታወሻ A5 ባለ new ገመድ',
            // 117, 'NoteBook A5 - ማስታወሻ A5 ባለ new ማግኔት',
            // 118, 'NoteBook A6 - 100 ማስታወሻ A6 100',
            // 119, 'NoteBook A6 - Magnet New ማስታወሻ A6 ማግኔት new',
            // 120, 'NoteBook A6 - Ribbon ማስታወሻ A6 ገመድ የድሮ',
            // 121, 'NoteBook A6 - ማስታወሻ A6 ባለ 1 ለእስክርቢቶ',
            // 122, 'NoteBook B5 - 2 with pen ማስታወሻ B5-2 ባለ እስክርቢቶ',
            // 123, 'NoteBook B5 - 4 Magnet Metal ማስታወሻ B5-4 ማግኔት ብረት',
            // 124, 'NoteBook B5 - Old ማስታወሻ የድሮ',
            // 125, 'Notebook - 9*7',
            // 126, 'Notebook A5 - ማስታወሻ ባለ ዉሃ',
            // 127, 'Noteit - (3*3/3*4/3*5)',
            // 128, 'Office Pin',
            // 129, 'Paint Brush የስዕል ብሩሽ',
            // 130, 'Paper Tray - (2/3) ማይካ',
            // 131, 'Paper Tray - 3 ብረት 2001',
            // 132, 'Pen - Bic Pen - (Black/Blue/Red) ቢክ እስኪብርቶ - (ጥቁር/ሰማያዊ/ቀይ)',
            // 133, 'Pen - Box Hello',
            // 134, 'Pen - Diamond ዳይመንድ እስኪብርቶ',
            // 135, 'Pencil - Color 2 sided',
            // 136, 'Pencil - Color እርሳስ ከለር አጭሩ',
            // 137, 'Pencil - Nann እርሳስ',
            // 138, 'Pencil - Vneeds እርሳስ',
            // 139, 'Pencil - እርሳስ ባለ እቃ',
            // 140, 'Pencil - እርሳስ የስዕል ቁጥሩ የተለያየ',
            // 141, 'Pencil - ጥቁር የስዕል እርሳስ',
            // 142, 'Pencil Bag - ሸራ ፔንስል ባግ',
            // 143, 'Pencil Bag - ፔንስል ባግ ማይካ ባለ መቅተጫ',
            // 144, 'Pencil Bag - ፔንስል ባግ ሻራ ጠንካራዉ',
            // 145, 'Plaster Cutter የእጅ ፕላስተር መቁረጫ ውዱ',
            // 146, 'Popit',
            // 147, 'Price Tag ዋጋ መለጠፊያ',
            // 148, 'Puncher - (ትንሹ/ትንቁ) 520',
            // 149, 'Puncher - Small ፓንቸር ትንሹ',
            // 150, 'Remover',
            // 151, 'Ring - ረንግ (6/8/10/12/14/16/18/20)',
            // 152, 'Rotring Eraser ሮተሪንግ ላጲስ',
            // 153, 'Ruler - 30 cm normal',
            // 154, 'Ruler - 30 cm ማስመሪያ 30 cm ጠንካራዉ',
            // 155, 'Ruler - 50 cm ማስመሪያ 50 cm',
            // 156, 'Ruler - Triangular Ruler 30 cm 144/288',
            // 157, 'Ruler - እርኬል ማስመሪያ',
            // 158, 'Scissor - Big መቀስ ትልቁ ባለክዳን',
            // 159, 'Scissor - Kids የህፃናት መቀስ',
            // 160, 'Scissor - Small ትንሹ መቀስ',
            // 161, 'Scissor - መካከለኝ መቀስ',
            // 162, 'Set Square - 35 cm ሴትእስኩዊር 35 cm',
            // 163, 'Set Square - Yellow ሲትስኬር ቢጫ',
            // 164, 'Set Square - ቢጫ ሴትስኬር ማርከር ያለዉ እና የሌለዉ',
            // 165, 'Sharpner - with a Brush ባለ ቡሩሽ መቅረጫ',
            // 166, 'Sharpner - መቅረጫ',
            // 167, 'Stapler - Gold',
            // 168, 'Stapler - Kangaroo (335/435)',
            // 169, 'Stapler - ርካሹ',
            // 170, 'Subject - (3/4/5)',
            // 171, 'Subject - A5 New',
            // 172, 'Subject - A5-11 ማስታወሻ ሄሎ Subject',
            // 173, 'T square 60cm',
            // 174, 'Ticket ትኬት',
            // 175, 'Transparency  - Color ትራንስፓረንሲ ከለር',
            // 176, 'Transparency - White ትራንስፓረንሲ ነጭ',
            // 177, 'Water Color',
            // 178, 'Water Color - ዉሃ ከለር ዉዱ ፍጭጭ የሚለዉ',
            // 179, 'ሰፈነግ (የብር መቁጠሪያ)',
            // 180, 'ሽት ትፖቴክተር',
            // 181, 'የስጦታ ማስታወሻ የተሰራ',
            // 182, 'የውብዳር ከለር',

            'Noteit',
            'Ring',
        ];$productNames = [
            // 1, '2025 - 1',
            // 2, '2025 - ብልጭልጭ',
            // 3, '25k - 1 ፓሪስ',
            // 4, '25k - 5 ጨርቅ ማስታወሻ',
            // 5, 'A3 - Laola',
            // 6, 'A3 - Road map',
            // 7, 'A4 - Binding file ዉዱ',
            // 8, 'A4 - Gold on',
            // 9, 'A4 - Laola',
            // 10, 'A4 - Post',
            // 11, 'A5 - 10 ባለቀለበት',
            // 12, 'A5 - 11 - 1 ጠንካራ ከቨር ያለዉ',
            // 13, 'A5 - 12 ባለ ፓኬት',
            // 14, 'A5 - 2 ባለ እስክርቢቶ',
            // 15, 'A5 - 5 ባለ ማብኔት ነጭ',
            // 16, 'A5 - 8 ባለሳንቲም ባለእስክርቢቶ',
            // 17, 'A5 - 9 ባለ ማግኔት ጌጥ',
            // 18, 'A5 - ብልጭልጭ 25k - 9',
            // 19, 'A5 - ገመድ new',
            // 20, 'A5 - ሳንቲም',
            // 21, 'A6 - 1 ባለ ገመድ',
            // 22, 'A6 - 1 ባለቁልፍ',
            // 23, 'A6 - 2 ባለ ገመድ',
            // 24, 'A6 - 2 ባለ ገመድ ብልጭልጭ ያለዉ',
            // 25, 'A6 - 3 ባለገመድ',
            // 26, 'A6 - ብልጭልጭ',
            // 27, 'A6 - ባለ ገመድ',
            // 28, 'A6 - ቁልፍ የድሮ',
            // 29, 'Acleric',
            // 30, 'Agenda አጀንዳ',
            // 31, 'Atlas Film አትላስ ፌልም',
            // 32, 'B5 - 1 ባለማግኔት ጫፉ ነጭ',
            // 33, 'B5 - 1 ሳንቲም',
            // 34, 'B5 - 2 ባለማግኔት ጌጥ',
            // 35, 'B5 - 3 ባለማግኔት ብረት',
            // 36, 'B5 - 5 ቀጭን ሳንቲም',
            // 37, 'B5 - ባለ ሳንቲም ኖርማል',
            // 38, 'B5 - ባለ ሳንቲም እስክርቢቶ ማስገቢያ ያለዉ',
            // 39, 'B5 - ሳንቲም',
            // 40, 'Bj ባለ 300 ብር',
            // 41, 'Box file - Black/Color',
            // 42, 'Business Card ቢዝነስ ካርድ',
            // 43, 'Cilp file',
            // 44, 'ClipBoard',
            // 45, 'ClipBoard - ክሊፕቦርድ ርካሹ',
            // 46, 'Color - 2 side Color',
            // 47, 'Color - Oil',
            // 48, 'Color - Piko ምሳቃ',
            // 49, 'Color - ምሳቃ ከለር ተንጠልጣይ',
            // 50, 'Color - ዉሃ ከለር ውዱ ትልቁ',
            // 51, 'Color Bad - 2 pockets ክሊር ባግ ባለ 2 ኪስ',
            // 52, 'Color Bag - ክሊር ባግ ርካሹ',
            // 53, 'Coloring Book',
            // 54, 'Coloring Book - ባለ ብሩሽ',
            // 55, 'Compass - 3009 ማይካ',
            // 56, 'Compass - 8005 ማይካ',
            // 57, 'Compass - 8010',
            // 58, 'Compass - Color b',
            // 59, 'Compass - Marshale',
            // 60, 'Compass - ቆርቆሮ ኮምፓስ',
            // 61, 'Compass - ጥቁር ኮምፓስ',
            // 62, 'Compass - ፕላስቲክ 5007',
            // 63, 'Crayon - Normal',
            // 64, 'Crayon - ምሳቃ ከለር በእቃ',
            // 65, 'Cutter - Small ከተር ትልቁ',
            // 66, 'Cutter - Small ከተር ትንሹ',
            // 67, 'Diary - Code ዲያሪ ኮድ',
            // 68, 'Diary - Small ዲያሪ ትንሹ',
            // 69, 'Diary - ዲያሪ ፍሩት',
            // 70, 'Diary - ዲያሪ የተለያየ',
            // 71, 'Dispencer big/Medium/small ዲስፔስር',
            // 72, 'Display book - 100',
            // 73, 'Display book - 40',
            // 74, 'Display book - 60',
            // 75, 'Display book - 80',
            // 76, 'Document Case',
            // 77, 'Drawing Book - Long የስዕል ደብተር ረጅሙ',
            // 78, 'Drawing Book - Short የስዕል ደብተር አጭሩ',
            // 79, 'Elastic Band - የብር ላስቲክ',
            // 80, 'Erasor Shaped ላጲስ ባለቅርፅ',
            // 81, 'Eyeye Pan',
            // 82, 'Fastener',
            // 83, 'Fixer (0.5/0.7) ፊክሰር (5/7) ቁጥር',
            // 84, 'Flexible 20cm',
            // 85, 'Fluid Normal',
            // 86, 'Folder - 12 pockets ፎልበር 12 ኪስ',
            // 87, 'Folder - 7 Pockets ባለ 7 ኪስ ፎልደር',
            // 88, 'Folder with rough texture ሸካራ ፎልደር',
            // 89, 'Globe ግሎብ',
            // 90, 'Hand Writing',
            // 91, 'Hard Cover',
            // 92, 'Laminating 65*95',
            // 93, 'Laminating 76*106',
            // 94, 'Laminating A3',
            // 95, 'Lead (0.5/0.7) ሊድ (0.5/0.7) ቁጥር',
            // 96, 'Magazine Rack - ማጋዚን ራክ የሚገጠም',
            // 97, 'Magazine Rack - መጋዘን ራክ የተበተነ',
            // 98, 'Marker - (1/2) Side',
            // 99, 'Marker - White Board',
            // 100, 'Marker - Yuanyuan',
            // 101, 'NoteBook - ማስታወሻ እንጨት',
            // 102, 'NoteBook - ጥጥ ማስታወሻ',
            // 103, 'NoteBook 18k - Black ማስታወሻ 18k ጥቁር',
            // 104, 'NoteBook 25k - Leather Expensive ማስታወሻ 25k ሌዘር ዉዱ',
            // 105, 'NoteBook 32k - Color',
            // 106, 'NoteBook 32k - Normal ማስታወሻ 32k normal',
            // 107, 'NoteBook 32k - ጥቁር',
            // 108, 'NoteBook 60k - ማስታወሻ 60k',
            // 109, 'NoteBook A4 - ማስታወሻ A4 መዝገብ 200',
            // 110, 'NoteBook A5 - 1 ማስታወሻ A5-1 ባለ ማግኔት',
            // 111, 'NoteBook A5 - 6 Magnet Metal ማስታወሻ A5- 6 ጫፉ ነጭ ብረት ማግኔት',
            // 112, 'NoteBook A5 - 7 Magnet Metal ማስታወሻ A5-7 ብረት ማግኔት',
            // 113, 'NoteBook A5 - Magnet New ማስታወሻ A5 ማግኔት new',
            // 114, 'NoteBook A5 - Metal Magnet ማስታወሻ A5 ብረት ማግኔት',
            // 115, 'NoteBook A5 - Paris ማስታወሻ A5 ፓሪስ',
            // 116, 'NoteBook A5 - ማስታወሻ A5 ባለ new ገመድ',
            // 117, 'NoteBook A5 - ማስታወሻ A5 ባለ new ማግኔት',
            // 118, 'NoteBook A6 - 100 ማስታወሻ A6 100',
            // 119, 'NoteBook A6 - Magnet New ማስታወሻ A6 ማግኔት new',
            // 120, 'NoteBook A6 - Ribbon ማስታወሻ A6 ገመድ የድሮ',
            // 121, 'NoteBook A6 - ማስታወሻ A6 ባለ 1 ለእስክርቢቶ',
            // 122, 'NoteBook B5 - 2 with pen ማስታወሻ B5-2 ባለ እስክርቢቶ',
            // 123, 'NoteBook B5 - 4 Magnet Metal ማስታወሻ B5-4 ማግኔት ብረት',
            // 124, 'NoteBook B5 - Old ማስታወሻ የድሮ',
            // 125, 'Notebook - 9*7',
            // 126, 'Notebook A5 - ማስታወሻ ባለ ዉሃ',
            // 127, 'Noteit - (3*3/3*4/3*5)',
            // 128, 'Office Pin',
            // 129, 'Paint Brush የስዕል ብሩሽ',
            // 130, 'Paper Tray - (2/3) ማይካ',
            // 131, 'Paper Tray - 3 ብረት 2001',
            // 132, 'Pen - Bic Pen - (Black/Blue/Red) ቢክ እስኪብርቶ - (ጥቁር/ሰማያዊ/ቀይ)',
            // 133, 'Pen - Box Hello',
            // 134, 'Pen - Diamond ዳይመንድ እስኪብርቶ',
            // 135, 'Pencil - Color 2 sided',
            // 136, 'Pencil - Color እርሳስ ከለር አጭሩ',
            // 137, 'Pencil - Nann እርሳስ',
            // 138, 'Pencil - Vneeds እርሳስ',
            // 139, 'Pencil - እርሳስ ባለ እቃ',
            // 140, 'Pencil - እርሳስ የስዕል ቁጥሩ የተለያየ',
            // 141, 'Pencil - ጥቁር የስዕል እርሳስ',
            // 142, 'Pencil Bag - ሸራ ፔንስል ባግ',
            // 143, 'Pencil Bag - ፔንስል ባግ ማይካ ባለ መቅተጫ',
            // 144, 'Pencil Bag - ፔንስል ባግ ሻራ ጠንካራዉ',
            // 145, 'Plaster Cutter የእጅ ፕላስተር መቁረጫ ውዱ',
            // 146, 'Popit',
            // 147, 'Price Tag ዋጋ መለጠፊያ',
            // 148, 'Puncher - (ትንሹ/ትንቁ) 520',
            // 149, 'Puncher - Small ፓንቸር ትንሹ',
            // 150, 'Remover',
            // 151, 'Ring - ረንግ (6/8/10/12/14/16/18/20)',
            // 152, 'Rotring Eraser ሮተሪንግ ላጲስ',
            // 153, 'Ruler - 30 cm normal',
            // 154, 'Ruler - 30 cm ማስመሪያ 30 cm ጠንካራዉ',
            // 155, 'Ruler - 50 cm ማስመሪያ 50 cm',
            // 156, 'Ruler - Triangular Ruler 30 cm 144/288',
            // 157, 'Ruler - እርኬል ማስመሪያ',
            // 158, 'Scissor - Big መቀስ ትልቁ ባለክዳን',
            // 159, 'Scissor - Kids የህፃናት መቀስ',
            // 160, 'Scissor - Small ትንሹ መቀስ',
            // 161, 'Scissor - መካከለኝ መቀስ',
            // 162, 'Set Square - 35 cm ሴትእስኩዊር 35 cm',
            // 163, 'Set Square - Yellow ሲትስኬር ቢጫ',
            // 164, 'Set Square - ቢጫ ሴትስኬር ማርከር ያለዉ እና የሌለዉ',
            // 165, 'Sharpner - with a Brush ባለ ቡሩሽ መቅረጫ',
            // 166, 'Sharpner - መቅረጫ',
            // 167, 'Stapler - Gold',
            // 168, 'Stapler - Kangaroo (335/435)',
            // 169, 'Stapler - ርካሹ',
            // 170, 'Subject - (3/4/5)',
            // 171, 'Subject - A5 New',
            // 172, 'Subject - A5-11 ማስታወሻ ሄሎ Subject',
            // 173, 'T square 60cm',
            // 174, 'Ticket ትኬት',
            // 175, 'Transparency  - Color ትራንስፓረንሲ ከለር',
            // 176, 'Transparency - White ትራንስፓረንሲ ነጭ',
            // 177, 'Water Color',
            // 178, 'Water Color - ዉሃ ከለር ዉዱ ፍጭጭ የሚለዉ',
            // 179, 'ሰፈነግ (የብር መቁጠሪያ)',
            // 180, 'ሽት ትፖቴክተር',
            // 181, 'የስጦታ ማስታወሻ የተሰራ',
            // 182, 'የውብዳር ከለር',

            'Noteit',
            'Ring',
        ];

        // Attach existing colors, sizes, and packaging types
        $colors = ItemColor::all();
        $sizes = ItemSize::all();
        $packagingTypes = ItemPackagingType::all();

        foreach ($productNames as $productName) {
            // Generate images
            $images = [
                asset("images/product_images/{$productName}_1.jpg"),
                asset("images/product_images/{$productName}_2.jpg"),
            ];

            // Create the item
            $item = Item::create([
                'product_name' => $productName,
                'product_description' => fake()->sentence(),
                'product_images' => json_encode($images),
                'status' => 'inactive', // All items start inactive
                'sold_count' => 0,
                'category_id' => rand(1, 10), // Adjust according to your categories
            ]);

            if ($colors->isEmpty() || $sizes->isEmpty() || $packagingTypes->isEmpty()) {
                throw new Exception('Seed colors, sizes, and packages first!');
            }

            $item->colors()->sync($colors->pluck('id')->toArray());
            $item->sizes()->sync($sizes->pluck('id')->toArray());
            $item->packagingTypes()->syncWithPivotValues(
                $packagingTypes->pluck('id')->toArray(), // just IDs
                ['quantity' => 1] // optional pivot value
            );

            // Generate all possible variants
            foreach ($colors as $color) {
                foreach ($sizes as $size) {
                    foreach ($packagingTypes as $pkg) {

                        ItemVariant::create([
                            'item_id' => $item->id,
                            'item_color_id' => $color->id,
                            'item_size_id' => $size->id,
                            'item_packaging_type_id' => $pkg->id,
                            'barcode' => null,
                            'images' => json_encode([]),
                            'status' => 'inactive',
                            // 'sku' => "{$item->sku}-{$color->code}-{$size->code}-{$pkg->code}-{$item->id}",
                        ]);
                    }
                }
            }
        }
    }
}
