services:
  duka_app:
    build:
      context: ..
    volumes:
      - ../:/var/www/html
      - storage_data:/var/www/html/storage
      - vendor_data:/var/www/html/vendor
      # 🎯 ADD THIS SUB-MOUNT OVERRIDE FOR PRODUCTION:
      - ../storage/app/seed-images:/var/www/html/storage/app/seed-images

    # Only expose HTTP/HTTPS
    ports:
      - "80:80"
      - "443:443"

    # Ensure correct env
    environment:
      APP_ENV: production

    # Restart policy (good for prod)
    restart: unless-stopped

  nginx_proxy:
      image: nginx:alpine
      ports:
        - "8080:80"  # We map this to 8080 on the host to avoid conflict
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - minio
      restart: unless-stopped