name: duka

services:
  duka_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: duka_app
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - duka-network

  db:
    image: mysql:8.0
    container_name: Duka_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - duka-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10

  minio:
    image: minio/minio
    container_name: Duka_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: your_strong_password
    restart: unless-stopped
    networks:
      - duka-network

  minio_setup:
      image: minio/mc:latest
      container_name: Duka_minio_setup
      depends_on:
        - minio
      networks:
        - duka-network
      entrypoint: >
        /bin/sh -c "
        echo 'Registering local server credentials...';
        until (/usr/bin/mc alias set local_setup http://Duka_minio:9000 admin your_strong_password) do echo 'Waiting for MinIO API endpoint...' && sleep 2; done;
        
        echo 'Creating duka-images bucket if missing...';
        /usr/bin/mc mb local_setup/duka-images --ignore-existing;
        
        echo 'Applying public anonymous download policy...';
        /usr/bin/mc anonymous set download local_setup/duka-images;
        
        echo '🚀 MinIO pipeline successfully completed!';
        exit 0;
        "

networks:
  duka-network:

volumes:
  database_data:
  vendor_data:
  storage_data:
  node_modules_data:
  minio_data: