services:
  duka_app:
    build:
      context: ..
    volumes:
      - ../:/var/www/html
      - storage_data:/var/www/html/storage
      - vendor_data:/var/www/html/vendor
      - ../storage/app/seed-images:/var/www/html/storage/app/seed-images
    ports:
      - "80:80"
      - "443:443"
    environment:
      APP_ENV: production
    restart: unless-stopped
    networks:
      - duka-network

  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - Duka_minio
    networks:
      - duka-network
    restart: unless-stopped

  Duka_minio:
    image: minio/minio
    container_name: Duka_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - duka-network
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: your_strong_password
    volumes:
      - minio_data:/data
    restart: unless-stopped

  minio_setup:
    image: minio/mc:latest
    container_name: Duka_minio_setup
    depends_on:
      - Duka_minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://Duka_minio:9000 admin your_strong_password; do
        echo 'Waiting for MinIO...';
        sleep 1;
      done;
      mc mb local/duka-images --ignore-existing;
      mc policy set public local/duka-images;
      echo '✅ MinIO bucket configured!';
      exit 0;
      "
    networks:
      - duka-network
    restart: "no"

networks:
  duka-network:
    driver: bridge

volumes:
  storage_data:
  vendor_data:
  minio_data: