name: duka

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: Duka_app
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - duka-network

  db:
    image: mysql:8.0
    container_name: Duka_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - duka-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  duka-network:

volumes:
  database_data:
  vendor_data:
  storage_data:
  node_modules_data:
