server {
    listen 80;
    server_name _;

    # This proxies requests from http://your-domain:8080/images/...
    # to http://minio:9000/...
    location /images/ {
        proxy_pass http://minio:9000/;
        proxy_set_header Host $http_host;
        proxy_buffering off;
        client_max_body_size 0;
    }
}