/**
 * `npm run tokens` (run inside the container).
 *
 * Writes, from resources/js/theme/*:
 *   resources/css/tokens.css                          CSS variables per role x mode
 *   resources/views/partials/theme-prepaint.blade.php  pre-paint data-mode/data-role script
 * and prints a contrast + hue report.
 *
 * `npm run tokens -- --swatches` also writes storage/app/swatches.html, a
 * static page (open it directly, no build) showing every role x mode.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { contrastRatio, oklchHue } from '../resources/js/theme/color';
import {
    buildPrepaintScript,
    COLOR_TOKENS,
    buildScheme,
    buildTokensCss,
    CONTRAST_PAIRS,
    contrastOf,
} from '../resources/js/theme/cssVars';
import { ROLES, type RoleKey } from '../resources/js/theme/roles';
import { ROLE_PALETTES, STATUS } from '../resources/js/theme/tokens';

const root = process.cwd();
const write = (rel: string, content: string) => {
    const abs = join(root, rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    console.log(`wrote ${rel}`);
};

const css = buildTokensCss();
write('resources/css/tokens.css', css);

const prepaint = buildPrepaintScript();
write(
    'resources/views/partials/theme-prepaint.blade.php',
    [
        '{{-- GENERATED by `npm run tokens` from resources/js/theme. Do not edit by hand. --}}',
        '{{-- Sets data-mode / data-role on <html> before first paint (no theme flash). --}}',
        '<script>',
        prepaint,
        '</script>',
        '',
    ].join('\n'),
);

// Every generated variable must be a Tailwind color name and vice versa.
// Loaded through Tailwind's own loader (jiti), exactly as the build loads it.
const loadConfig = createRequire(join(root, 'package.json'))('tailwindcss/loadConfig') as (path: string) => {
    theme: { extend: { colors: Record<string, string> } };
};
const twColors = Object.keys(loadConfig(join(root, 'tailwind.config.js')).theme.extend.colors);
const missingInTailwind = COLOR_TOKENS.filter((t) => !twColors.includes(t));
const missingInTokens = twColors.filter((t) => !(COLOR_TOKENS as string[]).includes(t));
if (missingInTailwind.length || missingInTokens.length) {
    console.error('tailwind.config.js colors and theme tokens disagree:', { missingInTailwind, missingInTokens });
    process.exitCode = 1;
} else {
    console.log(`tailwind.config.js: all ${COLOR_TOKENS.length} color names map to a token`);
}

// ---- Report ---------------------------------------------------------------

const modes = ['light', 'dark'] as const;
let failures = 0;
const contrastRows: { role: RoleKey; mode: string; fg: string; bg: string; ratio: number; min: number }[] = [];
for (const role of ROLES) {
    for (const mode of modes) {
        const s = buildScheme(role.key, mode);
        for (const [fg, bg, min] of CONTRAST_PAIRS) {
            const ratio = contrastOf(s, fg, bg);
            contrastRows.push({ role: role.key, mode, fg, bg, ratio, min });
            if (ratio < min) {
                failures++;
                console.log(`FAIL ${role.key}/${mode}: ${fg} on ${bg} = ${ratio.toFixed(2)} (< ${min})`);
            }
        }
    }
}
console.log(failures ? `${failures} contrast failure(s)` : 'contrast: all pairs pass');

const STATUS_HUES = Object.entries(STATUS).map(([name, pair]) => ({ name, ...oklchHue(pair.light) }));
const roleHues = ROLES.map((r) => ({ role: r.key, ...oklchHue(ROLE_PALETTES[r.key].primary.light) }));
const roleHuesDark = ROLES.map((r) => ({ role: r.key, ...oklchHue(ROLE_PALETTES[r.key].primary.dark) }));
const hueDist = (a: number, b: number) => {
    const d = Math.abs(a - b) % 360;
    return d > 180 ? 360 - d : d;
};
console.log('\nrole hues (OKLCH, light primary):');
for (const r of roleHues) {
    const nearest = roleHues
        .filter((o) => o.role !== r.role)
        .map((o) => ({ role: o.role, d: hueDist(r.h, o.h) }))
        .sort((a, b) => a.d - b.d)[0];
    const nearestStatus = STATUS_HUES.map((s) => ({ name: s.name, d: hueDist(r.h, s.h) })).sort((a, b) => a.d - b.d)[0];
    console.log(
        `  ${r.role.padEnd(13)} h=${r.h.toFixed(0).padStart(3)} c=${r.c.toFixed(3)} l=${r.l.toFixed(2)}  nearest role ${nearest.role} ${nearest.d.toFixed(0)}deg, nearest status ${nearestStatus.name} ${nearestStatus.d.toFixed(0)}deg`,
    );
}

console.log('dark primaries, nearest chromatic role (c > 0.1):');
for (const r of roleHuesDark.filter((x) => x.c > 0.1)) {
    const nearest = roleHuesDark
        .filter((o) => o.role !== r.role && o.c > 0.1)
        .map((o) => ({ role: o.role, d: hueDist(r.h, o.h) }))
        .sort((a, b) => a.d - b.d)[0];
    console.log(`  ${r.role.padEnd(13)} h=${r.h.toFixed(0).padStart(3)}  nearest ${nearest.role} ${nearest.d.toFixed(0)}deg`);
}

// ---- Swatches ---------------------------------------------------------------

if (process.argv.includes('--swatches')) {
    const rowsFor = (role: RoleKey, mode: string) =>
        contrastRows
            .filter((r) => r.role === role && r.mode === mode)
            .map(
                (r) =>
                    `<tr class="${r.ratio < r.min ? 'fail' : ''}"><td>${r.fg}</td><td>${r.bg}</td><td>${r.ratio.toFixed(2)}</td><td>${r.ratio >= r.min ? 'pass' : 'FAIL'} (${r.min})</td></tr>`,
            )
            .join('');
    const chips = () =>
        (Object.keys(STATUS) as (keyof typeof STATUS)[])
            .map(
                (n) =>
                    `<span class="chip" style="background:rgb(var(--${n}));color:rgb(var(--on-${n}))">${n}</span>` +
                    `<span class="chip" style="background:rgb(var(--${n}-container));color:rgb(var(--on-${n}-container))">${n} container</span>`,
            )
            .join('');
    const surfaces = [
        'surface-container-lowest',
        'surface-container-low',
        'surface-container',
        'surface-container-high',
        'surface-container-highest',
    ]
        .map((n) => `<div class="surf" style="background:rgb(var(--${n}))" title="${n}">${n.replace('surface-container', 'sc')}</div>`)
        .join('');

    const cards = ROLES.map((role) =>
        modes
            .map((mode) => {
                const s = buildScheme(role.key, mode);
                return `
<section class="card" data-role="${role.key}" data-mode="${mode}">
  <header><strong>${role.label}</strong> <code>${role.key}</code> &middot; ${mode}</header>
  <div class="row">
    <span class="btn bg-primary text-on-primary">bg-primary text-on-primary</span>
    <span class="btn" style="background:rgb(var(--primary-container));color:rgb(var(--on-primary-container))">primary-container</span>
    <span class="btn" style="background:rgb(var(--tertiary));color:rgb(var(--on-tertiary))">tertiary</span>
    <a href="#" style="color:rgb(var(--primary))">link text</a>
  </div>
  <div class="row hex">primary ${s.primary} &middot; on-primary ${s['on-primary']} &middot; container ${s['primary-container']} &middot; on-container ${s['on-primary-container']}</div>
  <div class="row">${surfaces}</div>
  <div class="row">${chips()}</div>
  <p style="color:rgb(var(--on-surface))">on-surface body text. <span style="color:rgb(var(--on-surface-variant))">on-surface-variant caption.</span></p>
  <input placeholder="outline border" style="border:1px solid rgb(var(--outline));background:rgb(var(--surface-container-lowest));color:rgb(var(--on-surface))">
  <table><thead><tr><th>fg</th><th>bg</th><th>ratio</th><th>AA</th></tr></thead><tbody>${rowsFor(role.key, mode)}</tbody></table>
</section>`;
            })
            .join(''),
    ).join('');

    const hueRows = roleHues
        .map((r) => {
            const pal = ROLE_PALETTES[r.role].primary;
            return `<tr><td>${r.role}</td><td><span class="dot" style="background:${pal.light}"></span>${pal.light}</td><td><span class="dot" style="background:${pal.dark}"></span>${pal.dark}</td><td>${r.h.toFixed(0)}</td><td>${r.c.toFixed(3)}</td><td>${r.l.toFixed(2)}</td></tr>`;
        })
        .join('');

    const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Duka role swatches</title>
<!-- GENERATED by \`npm run tokens -- --swatches\`. Uses the same CSS variables as the app (tokens.css is embedded below). -->
<style>
${css}
/* Mirrors what Tailwind generates for these two classes. */
.bg-primary { --tw-bg-opacity: 1; background-color: rgb(var(--primary) / var(--tw-bg-opacity)); }
.text-on-primary { --tw-text-opacity: 1; color: rgb(var(--on-primary) / var(--tw-text-opacity)); }
body { margin: 0; padding: 16px; font: 14px/1.4 system-ui, sans-serif; background: #e5e7eb; color: #111; }
h1 { font-size: 20px; } h2 { font-size: 16px; margin-top: 24px; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 520px), 1fr)); gap: 12px; }
.card { background: rgb(var(--background)); color: rgb(var(--on-surface)); border: 1px solid rgb(var(--outline-variant)); border-radius: 8px; padding: 12px; }
.card header { margin-bottom: 8px; }
.row { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; margin: 6px 0; }
.hex { font: 11px ui-monospace, monospace; color: rgb(var(--on-surface-variant)); }
.btn { padding: 6px 10px; border-radius: 4px; font-weight: 600; font-size: 12px; }
.chip { padding: 2px 8px; border-radius: 999px; font-size: 11px; font-weight: 600; }
.surf { flex: 1; min-width: 60px; padding: 8px 4px; font-size: 10px; text-align: center; border: 1px solid rgb(var(--outline-variant)); color: rgb(var(--on-surface-variant)); }
table { border-collapse: collapse; font-size: 11px; margin-top: 8px; width: 100%; }
td, th { border-bottom: 1px solid rgb(var(--outline-variant)); padding: 2px 4px; text-align: left; }
tr.fail td { color: #fff; background: #b91c1c; }
input { padding: 6px 8px; border-radius: 4px; }
.dot { display: inline-block; width: 12px; height: 12px; border-radius: 3px; margin-right: 6px; vertical-align: -2px; }
.hues td, .hues th { border-bottom: 1px solid #cbd5e1; }
</style>
</head>
<body>
<h1>Duka role swatches</h1>
<p>Every role x mode, rendered with the generated CSS variables. Contrast is WCAG 2 (text needs 4.5, outline/UI needs 3). Status hues: ${STATUS_HUES.map((s) => `${s.name} ${s.h.toFixed(0)}`).join(', ')} (OKLCH).</p>
<h2>Role hues (OKLCH of light primary)</h2>
<table class="hues"><thead><tr><th>role</th><th>light</th><th>dark</th><th>hue</th><th>chroma</th><th>lightness</th></tr></thead><tbody>${hueRows}</tbody></table>
<h2>Role x mode</h2>
<div class="grid">${cards}</div>
<p>${contrastRatio('#000000', '#ffffff').toFixed(0)}:1 is the maximum possible contrast.</p>
</body>
</html>
`;
    // docs/ is a separate repo beside the app, outside the container's mount.
    write('storage/app/swatches.html', html);
}
