/**
 * `npm run --silent design-md` (run inside the container).
 *
 * Prints docs/DESIGN.md to stdout: the design vocabulary an AI UI builder
 * (Google Stitch) may use, generated from source so it cannot drift:
 *   - color / type-scale / spacing / radius names  <- tailwind.config.js
 *   - role palettes, light and dark                <- resources/js/theme/*
 *   - shared components and their props            <- Components/Shared/ui (TS interfaces)
 *   - the StatusPill status -> tone map            <- Components/Shared/ui/StatusPill.tsx
 *
 * The host entry point is docs/scribts/build-design-md.sh, which runs this
 * through `docker exec`, checks the result and only then writes the file.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join } from 'node:path';
import ts from 'typescript';
import { STATUS_TONES } from '../resources/js/Components/Shared/ui/StatusPill';
import { TONES, type Tone } from '../resources/js/Components/Shared/ui/tones';
import { buildScheme, COLOR_TOKENS, DEFAULT_THEME_SETTING, THEME_STORAGE_KEY, type ColorToken } from '../resources/js/theme/cssVars';
import { DEFAULT_ROLE, ROLES } from '../resources/js/theme/roles';
import { NEUTRALS, ROLE_PALETTES, STATUS } from '../resources/js/theme/tokens';

const root = process.cwd();
const UI_DIR = 'resources/js/Components/Shared/ui';
const out: string[] = [];
const p = (...lines: string[]) => out.push(...lines);
const code = (s: string) => `\`${s}\``;
const list = (names: readonly string[]) => names.map(code).join(', ');

// ---- Sources ----------------------------------------------------------------

type FontSize = [string, { lineHeight?: string; letterSpacing?: string; fontWeight?: string }];
interface TwTheme {
    colors: Record<string, string>;
    fontSize: Record<string, FontSize>;
    spacing: Record<string, string>;
    borderRadius: Record<string, string>;
}
const loadConfig = createRequire(join(root, 'package.json'))('tailwindcss/loadConfig') as (path: string) => {
    darkMode: unknown;
    theme: { extend: TwTheme };
};
const tw = loadConfig(join(root, 'tailwind.config.js'));
const twx = tw.theme.extend;
const twColors = Object.keys(twx.colors);

// Fail rather than document names Tailwind would not generate.
const unknown = (COLOR_TOKENS as string[]).filter((t) => !twColors.includes(t));
const untokened = twColors.filter((t) => !(COLOR_TOKENS as string[]).includes(t));
if (unknown.length || untokened.length) {
    console.error('tailwind.config.js colors and theme tokens disagree; run `npm run tokens` first.', { unknown, untokened });
    process.exit(1);
}

// ---- Header -------------------------------------------------------------------

p(
    '# Duka ERP: design system brief',
    '',
    '> GENERATED by `docs/scribts/build-design-md.sh` from tailwind.config.js, resources/js/theme/*',
    `> and ${UI_DIR}/*. Do not edit by hand; edit those sources and re-run the script.`,
    '> Paste this whole file into Google Stitch before designing a screen (see docs/stitch-workflow.md).',
    '',
    '## 1. The app and the stack',
    '',
    'Multi-tenant ERP (retail, warehouse, delivery). One React app serves ten role subdomains plus a public',
    'storefront. Every module looks the same structurally; only the **accent color** changes per module, and',
    'every screen works in **light and dark** mode.',
    '',
    '- React 19 + Inertia.js + TypeScript (`.tsx`). **Tailwind CSS v3** (not v4) is the styling language for new screens.',
    '- Material UI 7 is still used for complex widgets (data tables, date pickers, charts). Do not design replacements for those.',
    '- Icons: **Material Symbols Outlined** (bundled), written as `<span className="material-symbols-outlined">inventory_2</span>`.',
    `- Font: Inter only (\`font-sans\`, and every type-scale name below uses Inter).`,
    '',
    '## 2. How color works (read this first)',
    '',
    'Colors are **semantic names** (Material 3 / Stitch vocabulary), never values. Each name is a CSS variable that',
    'changes with two attributes on `<html>`:',
    '',
    `- \`data-role="<role key>"\` picks the module accent (\`primary\`, \`tertiary\` and their variants). Set from the`,
    `  hostname before first paint; unknown hosts (root domain, login, storefront) use \`${DEFAULT_ROLE}\`.`,
    `- \`data-mode="light|dark"\` flips every neutral, surface and status color. Users choose light/dark/system`,
    `  (stored in \`localStorage['${THEME_STORAGE_KEY}']\`, default \`${DEFAULT_THEME_SETTING}\`).`,
    '- Any element carrying both attributes scopes its subtree to that role x mode (the dev showcase uses this).',
    '',
    'So `bg-primary text-on-primary` is orange on seller, indigo on admin, blue on stock keeper, and the lighter',
    'step of each in dark mode, with no code change. Opacity modifiers work: `bg-primary/10`, `border-outline-variant/70`.',
    'Because tokens already flip, **do not write `dark:` variants for colors**.',
    '',
);

// ---- Color names ---------------------------------------------------------------

const roleTokens = Object.keys(buildScheme(DEFAULT_ROLE, 'light')).filter(
    (t) => /primary|tertiary|surface-tint/.test(t),
);
const statusTokens = twColors.filter((t) => /(error|success|warning|info)/.test(t));
const neutralTokens = twColors.filter((t) => !roleTokens.includes(t) && !statusTokens.includes(t));
// Names that exist so Stitch output resolves, but that new screens should not reach for.
const m3Compat = (t: string) => /fixed|secondary|^inverse-primary$|^surface-(tint|dim|bright|variant)$/.test(t);

p(
    '## 3. Allowed color names',
    '',
    `Use these ${twColors.length} names with any Tailwind color utility: \`bg-\`, \`text-\`, \`border-\`, \`ring-\`, \`outline-\`,`,
    '`divide-`, `fill-`, `stroke-`, `from-`/`via-`/`to-`, `shadow-`, `placeholder-`, `accent-`, `caret-`.',
    '**No other color is allowed**: not Tailwind palette colors (`bg-slate-100`, `text-orange-700`, `bg-white`, `text-black`),',
    'not arbitrary values (`bg-[#c2410c]`), not hex/rgb in styles. `bg-transparent` and `currentColor` are fine.',
    '',
    `**Module accent (follows data-role):** ${list(roleTokens.filter((t) => !m3Compat(t) && !t.includes('tertiary')))}`,
    '',
    `**Second module accent** (\`tertiary\`; equals \`primary\` unless the role defines its own, e.g. dev's terminal green): ${list(
        roleTokens.filter((t) => !m3Compat(t) && t.includes('tertiary')),
    )}`,
    '',
    `**Surfaces and ink (shared by all modules):** ${list(neutralTokens.filter((t) => !m3Compat(t)))}`,
    '',
    `**Status (same hue in every module):** ${list(statusTokens)}`,
    '',
    `**Material 3 compatibility names** (resolve so Stitch output never loses styling; prefer the names above): ${list(
        twColors.filter(m3Compat),
    )}`,
    '',
    'What to use where:',
    '',
    '| Purpose | Classes |',
    '|---|---|',
    '| Page background | `bg-background` (or `bg-surface`) |',
    '| Card / panel | `bg-surface-container-lowest border border-outline-variant` |',
    '| Nested / hover / inset areas | `bg-surface-container-low`, `bg-surface-container`, `bg-surface-container-high` |',
    '| Body text / secondary text | `text-on-surface` / `text-on-surface-variant` |',
    '| Hairlines, dividers | `border-outline-variant`; input borders and muted icons `border-outline` / `text-outline` |',
    '| Primary button, active nav, links, focus | `bg-primary text-on-primary`, `text-primary`, `ring-primary` |',
    '| Soft accent fill (selected chip, highlight) | `bg-primary-container text-on-primary-container` |',
    '| Status solid / soft | `bg-success text-on-success` / `bg-success-container text-on-success-container` (same for error, warning, info) |',
    '| Tooltip, dark chip on light page | `bg-inverse-surface text-inverse-on-surface` |',
    '',
);

// ---- Palettes ----------------------------------------------------------------------

p(
    '## 4. Role palettes (reference values only; write the token name, never the hex)',
    '',
    '| Role key | Subdomain | Light `primary` / `primary-container` | Dark `primary` / `primary-container` |',
    '|---|---|---|---|',
);
for (const role of ROLES) {
    const l = buildScheme(role.key, 'light');
    const d = buildScheme(role.key, 'dark');
    const accent = ROLE_PALETTES[role.key].accent ? ` (+ \`tertiary\` ${l.tertiary} / ${d.tertiary})` : '';
    p(
        `| \`${role.key}\` | ${role.subdomains.map((s) => `${s}.`).join(', ')} | ${l.primary} / ${l['primary-container']} | ${d.primary} / ${d['primary-container']}${accent} |`,
    );
}
p('', `Login, public and storefront pages use \`${DEFAULT_ROLE}\`. Text on \`primary\` is always \`on-primary\` (white or ink, picked for contrast).`, '');

const keyNeutrals: ColorToken[] = [
    'background',
    'surface-container-lowest',
    'surface-container-low',
    'surface-container',
    'surface-container-high',
    'surface-container-highest',
    'on-surface',
    'on-surface-variant',
    'outline',
    'outline-variant',
];
p('Shared neutrals and status, light / dark:', '', '| Token | Light | Dark |', '|---|---|---|');
for (const t of keyNeutrals) {
    const pair = NEUTRALS[t as keyof typeof NEUTRALS];
    p(`| \`${t}\` | ${pair.light} | ${pair.dark} |`);
}
for (const [name, pair] of Object.entries(STATUS)) p(`| \`${name}\` | ${pair.light} | ${pair.dark} |`);
p('');

// ---- Type, spacing, radius ------------------------------------------------------

p(
    '## 5. Type scale, spacing, radius',
    '',
    'Type scale (`text-<name>`; each sets size, line height, weight and tracking, so do not add `font-*` on top):',
    '',
    '| Class | Size / line | Weight | Tracking |',
    '|---|---|---|---|',
);
const byPx = (a: [string, FontSize], b: [string, FontSize]) => parseFloat(b[1][0]) - parseFloat(a[1][0]);
for (const [name, [size, opts]] of Object.entries(twx.fontSize).sort(byPx)) {
    p(`| \`text-${name}\` | ${size} / ${opts.lineHeight ?? '-'} | ${opts.fontWeight ?? '-'} | ${opts.letterSpacing ?? '-'} |`);
}
p(
    '',
    'Standard Tailwind sizes (`text-xs`..`text-2xl`, `text-[11px]`) still work and are used by the shared components;',
    'prefer the named scale for new screens. `label-caps` is meant for uppercase labels (add `uppercase`).',
    '',
    `Extra spacing names (any spacing utility: \`p-\`, \`m-\`, \`gap-\`, \`space-y-\`, \`w-\`...): ${Object.entries(twx.spacing)
        .sort((a, b) => parseFloat(a[1]) - parseFloat(b[1]))
        .map(([k, v]) => `\`${k}\` ${v}`)
        .join(', ')}. The default numeric scale (\`p-4\`, \`gap-2\`) also works.`,
    '',
    `Radius (\`rounded-<name>\`): ${Object.entries(twx.borderRadius)
        .map(([k, v]) => `\`${k === 'DEFAULT' ? 'rounded' : `rounded-${k}`}\` ${v}`)
        .join(', ')}.`,
    'Note these are **smaller than stock Tailwind** (`rounded-full` is 0.75rem, not a pill). For pills and circles use',
    '`rounded-[999px]`; the hub look uses `rounded-[12px]` (rows, icon squares) and `rounded-[16px]` (cards).',
    '',
);

// ---- Components --------------------------------------------------------------------

const flat = (s: string) => s.replace(/\s+/g, ' ').trim();
const jsdoc = (node: ts.Node): string => {
    const docs = (node as unknown as { jsDoc?: ts.JSDoc[] }).jsDoc;
    if (!docs?.length) return '';
    return flat(ts.getTextOfJSDocComment(docs[docs.length - 1].comment) ?? '');
};

interface PropInfo {
    name: string;
    type: string;
    optional: boolean;
    doc: string;
    def?: string;
}
interface ComponentInfo {
    name: string;
    doc: string;
    propsName?: string;
    extendsText?: string;
    props: PropInfo[];
}

function readComponents(file: string): ComponentInfo[] {
    const src = ts.createSourceFile(file, readFileSync(join(root, file), 'utf8'), ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
    const interfaces = new Map<string, { extendsText?: string; props: PropInfo[] }>();
    const defaults = new Map<string, Map<string, string>>();
    const comps: { name: string; doc: string; propsName?: string }[] = [];
    const exported = (n: ts.Node) =>
        ts.canHaveModifiers(n) && (ts.getModifiers(n) ?? []).some((m) => m.kind === ts.SyntaxKind.ExportKeyword);

    for (const st of src.statements) {
        if (ts.isInterfaceDeclaration(st) && exported(st)) {
            interfaces.set(st.name.text, {
                extendsText: st.heritageClauses?.map((h) => flat(h.types.map((t) => t.getText(src)).join(', '))).join(', '),
                props: st.members.filter(ts.isPropertySignature).map((m) => ({
                    name: m.name.getText(src),
                    type: flat(m.type?.getText(src) ?? 'unknown'),
                    optional: !!m.questionToken,
                    doc: jsdoc(m),
                })),
            });
        }
        // Exported PascalCase functions are components; also collect their
        // destructuring defaults. Lower-case helpers (ActionRow, Card internals) are skipped.
        if (ts.isFunctionDeclaration(st) && st.name && st.body) {
            const param = st.parameters[0];
            const typeName = param?.type && ts.isTypeReferenceNode(param.type) ? param.type.typeName.getText(src) : undefined;
            if (param && ts.isObjectBindingPattern(param.name)) {
                const map = new Map<string, string>();
                for (const el of param.name.elements) {
                    if (el.initializer) map.set((el.propertyName ?? el.name).getText(src), flat(el.initializer.getText(src)));
                }
                if (typeName) {
                    const prev = defaults.get(typeName) ?? new Map();
                    for (const [k, v] of map) if (!prev.has(k)) prev.set(k, v);
                    defaults.set(typeName, prev);
                }
            }
            if (exported(st) && /^[A-Z]/.test(st.name.text)) comps.push({ name: st.name.text, doc: jsdoc(st), propsName: typeName });
        }
    }

    return comps.map((c) => {
        const iface = c.propsName ? interfaces.get(c.propsName) : undefined;
        const defs = c.propsName ? defaults.get(c.propsName) : undefined;
        return {
            ...c,
            extendsText: iface?.extendsText,
            props: (iface?.props ?? []).map((pr) => ({ ...pr, def: defs?.get(pr.name) })),
        };
    });
}

const uiFiles = readdirSync(join(root, UI_DIR))
    .filter((f) => f.endsWith('.tsx'))
    .sort()
    .map((f) => `${UI_DIR}/${f}`);
const components = uiFiles.flatMap(readComponents);
if (!components.length) {
    console.error(`no components found in ${UI_DIR}`);
    process.exit(1);
}

const indexSrc = readFileSync(join(root, UI_DIR, 'index.ts'), 'utf8');
const helperExports = [...indexSrc.matchAll(/export\s*\{([^}]*)\}/g)]
    .flatMap((m) => m[1].split(','))
    .map((s) => s.trim())
    .filter((s) => s && !s.startsWith('type ') && !components.some((c) => c.name === s));

p(
    '## 6. Shared components (reuse these instead of re-drawing them)',
    '',
    `Import from \`@/Components/Shared/ui\`. They use only the tokens above, so they follow the role color and mode.`,
    'When a Stitch design shows a header, a stat tile grid, a list of link rows, a card, a status badge or an empty',
    'state, map it to these. Live preview of every state, per role and mode: dev subdomain, `/design-system`.',
    '',
);
for (const c of components) {
    p(`### \`<${c.name}>\``, '');
    if (c.doc) p(c.doc, '');
    if (c.extendsText) p(`Also accepts every prop of \`${c.extendsText}\`.`, '');
    if (c.props.length) {
        p('| Prop | Type | Default | Notes |', '|---|---|---|---|');
        for (const pr of c.props) {
            const t = pr.type.replace(/\|/g, '\\|');
            p(`| \`${pr.name}${pr.optional ? '?' : ''}\` | \`${t}\` | ${pr.def ? `\`${pr.def}\`` : ''} | ${pr.doc.replace(/\|/g, '\\|')} |`);
        }
        p('');
    }
}
p(`Also exported: ${list(helperExports)}.`, '');

// ---- Tones and statuses -----------------------------------------------------------

p(
    '## 7. Tones and the status map',
    '',
    '`tone` props (StatCard, ActionTile, StatusPill) take one of these; each maps to token classes:',
    '',
    '| Tone | Solid (`badge`) | Soft (`pill`) |',
    '|---|---|---|',
);
for (const [tone, set] of Object.entries(TONES)) p(`| \`${tone}\` | \`${set.badge}\` | \`${set.pill}\` |`);
p(
    '',
    '`<StatusPill status="..." />` colors a status the same way in every module. Unknown statuses are `neutral`.',
    'Design status badges with these meanings; do not invent per-screen status colors.',
    '',
);
const byTone = new Map<Tone, string[]>();
for (const [status, tone] of Object.entries(STATUS_TONES)) byTone.set(tone, [...(byTone.get(tone) ?? []), status]);
for (const [tone, statuses] of byTone) p(`- **${tone}**: ${statuses.join(', ')}`);
p('');

// ---- Modules and layouts -------------------------------------------------------------

p(
    '## 8. Modules',
    '',
    'Each module page is wrapped by its layout (app bar, nav). Design the page body, not the shell.',
    '',
    '| Module | Role key | Layout | Form factor |',
    '|---|---|---|---|',
);
const MOBILE = new Set(['stock_keeper', 'delivery']);
for (const role of ROLES) {
    const layout = `${role.label}Layout`;
    const has = existsSync(join(root, `resources/js/Layouts/${layout}.tsx`));
    p(
        `| ${role.label} | \`${role.key}\` | ${has ? `\`${layout}\`` : '(none yet)'} | ${MOBILE.has(role.key) ? '**mobile-first** (phones on the floor)' : 'desktop-first, must work on tablets'} |`,
    );
}
p(
    `| Storefront (public shop) | (\`${DEFAULT_ROLE}\` colors) | none, composes \`Components/Storefront/*\` | **mobile-first** (480px shell on phones) |`,
    '',
);

// ---- Rules --------------------------------------------------------------------------

p(
    '## 9. Rules for generated screens',
    '',
    '1. **Colors: only the names in section 3.** No hex, `rgb()`, `hsl()`, arbitrary color values (`bg-[#...]`) or',
    '   Tailwind palette colors (`slate-*`, `orange-*`, `white`, `black`). A CI-style check (`npm run check:colors`) rejects new hex/rgb literals.',
    '2. **Never hard-code a module color.** Use `primary` / `primary-container`; the same markup must work in every module.',
    '3. **No inline styles** (`style={{...}}`). Tailwind classes only.',
    '4. **Icons: Material Symbols** as `<span className="material-symbols-outlined">icon_name</span>`; size with `text-[20px]` etc.',
    '   No inline SVG icon sets, no other icon fonts.',
    '5. **Reuse the shared components** in section 6 for headers, stat tiles, link rows, cards, section titles, status',
    '   badges and empty states. Use the status map in section 7 for any status badge.',
    '6. **Tailwind v3 syntax only.** No v4 syntax (`@theme`, `@import "tailwindcss"`, the `bg-(--var)` shorthand).',
    '7. **Light and dark both work automatically.** Do not add `dark:` color variants; tokens already flip. Use `dark:` only',
    '   for a justified non-color tweak (e.g. hiding a decorative image), and say why.',
    '8. **Mobile-first for stock keeper, delivery and the storefront**: design at 360-480px first, touch targets >= 44px,',
    '   primary actions within thumb reach. Other modules are desktop-first but must not break on a tablet.',
    '9. Use the type scale and spacing names in section 5; keep the radius small (`rounded-[12px]` rows, `rounded-[16px]` cards).',
    '10. Keep data fields and actions from the existing screen; a redesign changes presentation, not behavior.',
    '11. Leave data tables, date pickers and charts as placeholders: those stay Material UI components.',
    '',
);

process.stdout.write(out.join('\n'));
